# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          VER=21.01.14.108
          DEB=roswell_${VER}-1_amd64.deb
          apt-get -y update && apt-get -y upgrade
          apt-get install -y libssl-dev libcurl3 apt-utils man sudo make wget bzip2 libyaml-0-2 rlwrap emacs-nox libreadline-dev
          wget https://github.com/roswell/roswell/releases/download/v${VER}/${DEB}
          dpkg -i ${DEB} && rm ${DEB} && apt-get clean
          ros install quicklisp-slime-helper hunchentoot hunchensocket cl-who parenscript
          ros run -e '(ql-dist:install-dist "http://dist.ultralisp.org/" :prompt nil)' -q
          mkdir -p ~/common-lisp && ros install val314159/ly val314159/r2
